 name: TOOLBOXLAP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # إعادة التشغيل التلقائي كل 6 ساعات

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    # استخدام التخزين المؤقت لتجنب إعادة التنزيل
    - name: Cache Playit Agent
      uses: actions/cache@v3
      with:
        path: C:\Program Files\Playit\playit.exe
        key: playit-v0.15.26

    - name: Download and Install Playit if not cached
      run: |
        if (!(Test-Path "C:\Program Files\Playit\playit.exe")) {
          Write-Host "Playit not found, installing..."
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "C:\Program Files\Playit\playit.exe"
        }
        Start-Sleep -Seconds 5  # وقت للتحميل
    
    # إعداد RDP
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

    - name: Run Playit Agent
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
      run: |
        Start-Process -FilePath "C:\Program Files\Playit\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "C:\Program Files\Playit\playit.exe" -NoNewWindow

    # إبقاء الجلسة نشطة لأطول فترة ممكنة
    - name: Keep the GitHub Action Runner Alive
      run: |
        while ($true) { Start-Sleep -Seconds 3600 }  # إبقاء الجلسة نشطة بشكل مستمر
